/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WorkspaceProvidersIndexRouteImport } from './routes/_workspace/providers.index'
import { Route as WorkspaceProvidersServiceRouteImport } from './routes/_workspace/providers.$service'
import { Route as WorkspaceSyncsIndexRouteImport } from './routes/_workspace/syncs.index'
import { Route as WorkspaceSyncsIdRouteImport } from './routes/_workspace/syncs.$id'
import { Route as WorkspaceSyncsNewRouteImport } from './routes/_workspace/syncs.new'
import { Route as WorkspaceSyncsIdDeliverablesDeliveryIdRouteImport } from './routes/_workspace/syncs.$id_.deliverables.$deliveryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceProvidersIndexRoute = WorkspaceProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceProvidersServiceRoute =
  WorkspaceProvidersServiceRouteImport.update({
    id: '/providers/$service',
    path: '/providers/$service',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceSyncsIndexRoute = WorkspaceSyncsIndexRouteImport.update({
  id: '/syncs/',
  path: '/syncs/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSyncsIdRoute = WorkspaceSyncsIdRouteImport.update({
  id: '/syncs/$id',
  path: '/syncs/$id',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSyncsNewRoute = WorkspaceSyncsNewRouteImport.update({
  id: '/syncs/new',
  path: '/syncs/new',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSyncsIdDeliverablesDeliveryIdRoute =
  WorkspaceSyncsIdDeliverablesDeliveryIdRouteImport.update({
    id: '/syncs/$id_/deliverables/$deliveryId',
    path: '/syncs/$id/deliverables/$deliveryId',
    getParentRoute: () => WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/providers/$service': typeof WorkspaceProvidersServiceRoute
  '/syncs/$id': typeof WorkspaceSyncsIdRoute
  '/syncs/new': typeof WorkspaceSyncsNewRoute
  '/providers/': typeof WorkspaceProvidersIndexRoute
  '/syncs/': typeof WorkspaceSyncsIndexRoute
  '/syncs/$id/deliverables/$deliveryId': typeof WorkspaceSyncsIdDeliverablesDeliveryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/providers/$service': typeof WorkspaceProvidersServiceRoute
  '/syncs/$id': typeof WorkspaceSyncsIdRoute
  '/syncs/new': typeof WorkspaceSyncsNewRoute
  '/providers': typeof WorkspaceProvidersIndexRoute
  '/syncs': typeof WorkspaceSyncsIndexRoute
  '/syncs/$id/deliverables/$deliveryId': typeof WorkspaceSyncsIdDeliverablesDeliveryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/login': typeof LoginRoute
  '/_workspace/providers/$service': typeof WorkspaceProvidersServiceRoute
  '/_workspace/syncs/$id': typeof WorkspaceSyncsIdRoute
  '/_workspace/syncs/new': typeof WorkspaceSyncsNewRoute
  '/_workspace/providers/': typeof WorkspaceProvidersIndexRoute
  '/_workspace/syncs/': typeof WorkspaceSyncsIndexRoute
  '/_workspace/syncs/$id_/deliverables/$deliveryId': typeof WorkspaceSyncsIdDeliverablesDeliveryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/providers/$service'
    | '/syncs/$id'
    | '/syncs/new'
    | '/providers/'
    | '/syncs/'
    | '/syncs/$id/deliverables/$deliveryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/providers/$service'
    | '/syncs/$id'
    | '/syncs/new'
    | '/providers'
    | '/syncs'
    | '/syncs/$id/deliverables/$deliveryId'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/login'
    | '/_workspace/providers/$service'
    | '/_workspace/syncs/$id'
    | '/_workspace/syncs/new'
    | '/_workspace/providers/'
    | '/_workspace/syncs/'
    | '/_workspace/syncs/$id_/deliverables/$deliveryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/providers/': {
      id: '/_workspace/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof WorkspaceProvidersIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/providers/$service': {
      id: '/_workspace/providers/$service'
      path: '/providers/$service'
      fullPath: '/providers/$service'
      preLoaderRoute: typeof WorkspaceProvidersServiceRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/syncs/': {
      id: '/_workspace/syncs/'
      path: '/syncs'
      fullPath: '/syncs/'
      preLoaderRoute: typeof WorkspaceSyncsIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/syncs/$id': {
      id: '/_workspace/syncs/$id'
      path: '/syncs/$id'
      fullPath: '/syncs/$id'
      preLoaderRoute: typeof WorkspaceSyncsIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/syncs/new': {
      id: '/_workspace/syncs/new'
      path: '/syncs/new'
      fullPath: '/syncs/new'
      preLoaderRoute: typeof WorkspaceSyncsNewRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/syncs/$id_/deliverables/$deliveryId': {
      id: '/_workspace/syncs/$id_/deliverables/$deliveryId'
      path: '/syncs/$id/deliverables/$deliveryId'
      fullPath: '/syncs/$id/deliverables/$deliveryId'
      preLoaderRoute: typeof WorkspaceSyncsIdDeliverablesDeliveryIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceProvidersServiceRoute: typeof WorkspaceProvidersServiceRoute
  WorkspaceSyncsIdRoute: typeof WorkspaceSyncsIdRoute
  WorkspaceSyncsNewRoute: typeof WorkspaceSyncsNewRoute
  WorkspaceProvidersIndexRoute: typeof WorkspaceProvidersIndexRoute
  WorkspaceSyncsIndexRoute: typeof WorkspaceSyncsIndexRoute
  WorkspaceSyncsIdDeliverablesDeliveryIdRoute: typeof WorkspaceSyncsIdDeliverablesDeliveryIdRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceProvidersServiceRoute: WorkspaceProvidersServiceRoute,
  WorkspaceSyncsIdRoute: WorkspaceSyncsIdRoute,
  WorkspaceSyncsNewRoute: WorkspaceSyncsNewRoute,
  WorkspaceProvidersIndexRoute: WorkspaceProvidersIndexRoute,
  WorkspaceSyncsIndexRoute: WorkspaceSyncsIndexRoute,
  WorkspaceSyncsIdDeliverablesDeliveryIdRoute:
    WorkspaceSyncsIdDeliverablesDeliveryIdRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
